; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.20"

; Modules
projects[ctools][version] = "1.2"

projects[entity][version] = "1.0"

projects[features][version] = "2.0-beta1"

projects[i18n][version] = "1.8"

projects[l10n_update][version] = "1.0-beta3"

projects[location][version] = "3.0-alpha1"

projects[strongarm][version] = "2.0"

projects[variable][version] = "2.2"

projects[views][version] = "3.5"

projects[profile2][version] = "1.3"

projects[field_group][version] = "1.1"

projects[rel][version] = "1.0-alpha2"

projects[ds][version] = "2.2"


; Themes
projects[simpleclean][version] = "1.4"

