; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.20"

; Modules
projects[ctools][version] = "1.2"

projects[entity][version] = "1.0"

projects[features][version] = "2.0-beta1"

projects[i18n][version] = "1.8"

projects[l10n_update][version] = "1.0-beta3"

projects[l10n_client][version] = "1.2"

projects[location][version] = "3.0-alpha1"

projects[strongarm][version] = "2.0"

projects[variable][version] = "2.2"

projects[views][version] = "3.5"

projects[openlayers][version] = "2.0-beta5"

projects[profile2][version] = "1.3"

projects[field_group][version] = "1.1"

projects[realname][version] = "1.1"

projects[token][version] = "1.5"

projects[rel][version] = "1.0-alpha2"

projects[ds][version] = "2.2"

projects[backup_migrate][version] = "2.4"

projects[uif][version]  = "1.5"
projects[uif_plus][version] = "1.2"

projects[fontyourface][version] = "2.7"

; Themes
projects[simpleclean][version] = "1.4"

; Themes
projects[fillform][download][type] = "git"
projects[fillform][download][url] = "git://github.com/dominikb1888/fillformtheme.git"
projects[fillform][type] = "theme"

; Features
projects[fillform_international][download][type] = "git"
projects[fillform_international][download][url] = "git@redmine.wi1projects.com:fillform/fillform-international.git"
projects[fillform_international][type] = "module"
projects[fillform_international][subdir] = "cfeatures"

projects[fillform_greetings][download][type] = "git"
projects[fillform_greetings][download][url] = "git@redmine.wi1projects.com:fillform/fillform-greetings.git"
projects[fillform_greetings][type] = "module"
projects[fillform_greetings][subdir] = "cfeatures"


; Custom Modules
projects[uif_plus_location][download][type] = "git"
projects[uif_plus_location][download][url] = "git@redmine.wi1projects.com:custommodules/uif-plus-location.git"
projects[uif_plus_location][type] = "module"
